(lang dune 3.6)

; (name tp1)

; (generate_opam_files false)

; (package
;  (name tp1)
;  (allow_empty))

(name tp2)

(generate_opam_files false)

(package
 (name tp2)
 (allow_empty))

(package
 (name gcpLib)
 (allow_empty))
