// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("./stdlib/list.js");

function f(l) {
  return List.map((function (prim) {
                return prim + 1 | 0;
              }), l);
}

exports.f = f;
/* No side effect */